### ISSUE TITLE
_vshSblAimgrGetConsoleId doesn't appear in the search

### ISSUE THREAD

**Issue by windsurfer1122** [vitasdk/vita-headers#418] opened 2019-08-20 21:54 UTC
[MajorTomSec][1] already did this and would be nice if this could be added to the SDK.
https://github.com/MajorTomSec/VitaCID/tree/master/extra

[1]: https://github.com/MajorTomSec/VitaCID "VitaCID by MajorTomSec"

**Comment by Princess-of-Sleeping** [comment] 2019-08-20 22:11
You just fork vita_header and add a function and make a pull request

**Comment by windsurfer1122** [comment] 2019-08-20 22:13
This would be I would know how to extend the Vita SDK :)
Will have a look.

**Comment by windsurfer1122** [comment] 2019-08-20 22:30
After digging through the Vita SDK source I found that it is already available:
Include: https://github.com/vitasdk/vita-headers/blob/master/include/psp2/vshbridge.h#L18
Library: `SceVshBridge_stub`

It is just not listed in the [docs](https://docs.vitasdk.org/).

**Comment by Princess-of-Sleeping** [comment] 2019-08-20 22:50
Although listed exactly, there is no description in the documentation because there is no function description in the header

https://docs.vitasdk.org/group__SceVshBridgeUser.html#gab437d640375011bed4c7a1a332329ef3

**Comment by windsurfer1122** [comment] 2019-08-20 23:15
And the search function also does not find that line when searching for "_vshSblAimgrGetConsoleId" or just "ConsoleID" :(

**Comment by Princess-of-Sleeping** [comment] 2019-08-21 00:06
Strange

**Comment by windsurfer1122** [comment] 2019-08-26 21:50
Same with "printf" and "sceClibSnprintf" both not found.
Windows with Firefox 68.0.2 and Chrome 76.0.3809.100.
Result should be: https://docs.vitasdk.org/group__SceCLibUser.html

But "psid" works.

Seems the search does not consider all available data.

**Comment by Princess-of-Sleeping** [comment] 2019-08-26 21:52
It is recommended to search db.yml directly

**Comment by devnoname120** [comment] 2019-09-25 14:08
Functions without documentation (those that can't be clicked on in Doxygen) don't appear in the search. Might be fixed by tweaking the documentation [config](https://github.com/vitasdk/vita-headers/blob/master/docs/Doxyfile) or updating Doxygen.

**Comment by devnoname120** [comment] 2019-09-25 15:48
This issue is fixed thanks to https://github.com/vitasdk/vita-headers/pull/421.

**Comment by devnoname120** [comment] 2019-09-25 15:49
Duplicate of https://github.com/vitasdk/vita-headers/issues/111.

**Closed by devnoname120** 2019-09-25 15:49 UTC
Labels: duplicate
